### PR TITLE
Use only constant global class loaders to initialize the global resolver

### LINKED ISSUE #450: ConfigProviderResolver wrongly uses TCCL in a static context
The `ConfigProviderResolver` class resolves a singleton instance based on whatever the context class loader was set to when the method was called.  This essentially means that the behavior of the singleton global resolver will depend entirely on when and how that method is first called.

The TCCL should not be consulted when constructing the global resolver instance.

The only correct solution would be to use a globally available, constant (static) class loader.  The following are available, and could be tried in order:

* The class's own class loader (this works in an environment such as WildFly where module dependencies are explicitly declared, or in flat classpath situations)
* The JDK application class loader (this works in an environment where the implementation is visible from the application class loader)
* The JDK platform class loader (this is technically already be visible from the application class loader so it does not need to be explicitly tried)

### PR DESCRIPTION
**Pull request by dmlloyd**
Fixes #450

Signed-off-by: David M. Lloyd <david.lloyd@redhat.com>

### CODE REVIEW

**Comment by genie-microprofile** [comment]
Can one of the admins verify this patch?

**Comment by Emily-Jiang** [comment]
@genie-microprofile please test

**Comment by dmlloyd** [comment]
Updated to fix wrong issue reference.

File: api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java [hunk 1]
```diff
@@ -105,39 +103,25 @@ public static ConfigProviderResolver instance() {
                 if (instance != null) {
                     return instance;
                 }
+                // first try my class loader
+                ConfigProviderResolver instance = loadSpi(ConfigProviderResolver.class.getClassLoader(), null);
+                // next try the system class loader
+                instance = loadSpi(null, instance);
```
Comment (Emily-Jiang) [inline api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java]: Your change will bypass the ThreadContextClassloader, as you try to use the classloader from ConfigProviderResolver or the system classloader, which might not the right classloader.

Comment (Emily-Jiang) [reply api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java]: @struberg @OndroMih Can you please check against your implementation?

Comment (dmlloyd) [reply api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java]: That is correct. There *is* no correct thread context classloader in a static initializer, because there is no way to guarantee who the caller is - it can vary between runs even.  It is never correct to reference TCCL or any thread local value from a static initializer.

Comment (OndroMih) [reply api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java]: It makes sense, @dmlloyd. When I look at it now, @Emily-Jiang, I think it's enough to have a single ConfigProviderResolver instance per JVM as it doesn't hold any state. In the end, the concrete implementation of `ConfigProviderResolver` can load the Config instance using the thread context classloader as it's done in Payara already: https://github.com/payara/Payara/blob/master/nucleus/payara-modules/nucleus-microprofile/config-service/src/main/java/fish/payara/nucleus/microprofile/config/spi/ConfigProviderResolverImpl.java. I would have to review it more thoroughly but I think that Payara doesn't expect that the implementation of ConfigProviderResolver is loaded by any specific classloader.

Comment (OndroMih) [inline api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java]: I'm really not sure if it makes sense to load the resolver by both the resolver's classloader and the system classloader. I'm afraid that if the resolver impl is in the system classloader and if resolver's classloader delegates to the system classloader, the same impl would be found in both classloaders and that would end with an exception "Multiple ConfigResolverProvider implementations found". Is it really necessary to try loading also with the system classloader? In which relevant case the resolver's classloader doesn't delegate to the system classloader so that the resolver impl isn't found and needs to be looked up by the system classloader? I would delete the call to loadSpi using the system classloader and only rely on the resolver's classloader.

Comment (dmlloyd) [reply api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java]: I would be happy to revise this patch to only consider the implementation's own class loader.  It would simplify the change.

Comment (OndroMih) [reply api/src/main/java/org/eclipse/microprofile/config/spi/ConfigProviderResolver.java]: We've tested this PR with the current Payara implementation and all seems to work. It passes the MP TCK. So we approve this PR.

**Comment by kenfinnigan** [comment]
good to merge?
